fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "inifile": "git://github.com/cprice-puppet/puppetlabs-inifile"
    "keystone": "git://github.com/stackforge/puppet-keystone.git"
    "mysql":
      repo: "git://github.com/puppetlabs/puppetlabs-mysql.git"
      ref:  'origin/0.x'
    "nova": "git://github.com/stackforge/puppet-nova.git"
    "vswitch": "git://github.com/bodepd/puppet-vswitch"
  symlinks:
    "quantum": "#{source_dir}"
