name    'puppet-neutron'
version '2.1.1'
source  'https://github.com/CiscoSystems/puppet-neutron'
author  'Joe Topjian,Endre Karlson,Emilien Macchi,Dan Bode,Dmitry Ukov,Edgar Mangana,Robert Starmer,Ian Wells,Daneyon Hansen'
license 'Apache License 2.0'
summary 'Puppet module for OpenStack Neutron'
description 'Puppet module to install and configure the OpenStack network service, Neutron'
project_page 'https://github.com/stackforge/puppet-neutron'

# Dependencies
dependency 'puppetlabs/vswitch', '>=0.0.1 <1.0.0'
dependency 'puppetlabs/inifile', '>=1.0.0 <2.0.0'
dependency 'puppetlabs/mysql', '>=0.6.1 <1.0.0'
dependency 'puppetlabs/stdlib', '>=2.3.0'
dependency 'puppetlabs/keystone', '>=2.0.0 <3.0.0'
dependency 'puppetlabs/nova', '>=2.0.0 <3.0.0'
